### ISSUE TITLE
Kodlama stili hazırla

### ISSUE THREAD

**Issue by roktas** [uzem/tbs#1]
Rubocop ile Ruby + Rails kodlama stili için bu projeyi pilot yapalım.

@emredemir gerekirse checklist ile bu görevi aç, gerekmiyorsa kapat.

**Comment by msdundar** [comment]
@emredemir öğrenme amaçlı reek'e de göz atabilirsin: https://github.com/troessner/reek

ama standart olması ve kullanılması gereken kesinlikle rubocop.

**Comment by emredemir** [comment]
Ruby için stiller eklendi @roktas @msdundar.
