### ISSUE TITLE
Kimlik doğrulama ve ubsden veri çekme

### ISSUE THREAD

**Issue by sinansahin** [uzem/tbs#17]
Projeyi incelediğimde öğrenci login işlemleri ubs üzerinden, akademik ve idari personelin login işlemleri ise local db üzerinden yürütülüyor. Kullanıcı adı "o" ile başlıyorsa öğrenci yani ubs ye gidecek, kullanıcı adı 11 haneli ise local db den kontrol edilicek şeklinde bir mantık kurulmuş. Burası için bundan başka güzel bir çözüm metodu var. Üniversitemizdeki bütün öğrencilerin ve personelin kurumsal e-posta adresleri ve dolayısıyla bir LDAP servisi var. 

**Neden LDAP üzerinden gidilmeli ?** 
* db de hiç bir şekilde password tutmanıza gerek kalmaz. Bu da güvenliğini artırır. 
* Öğrenci kullanıcı adı kısmına "o" yazmak zorunda değildir ve bırakılmamalı. İlerde aktif kullanılan UBS değişse bile öğrenci LDAP'ı kolay kolay değişmez, değişmemeli (Bknz, ODTÜ ve ldap kullanan diğer üniversiteler - istisnalar hariç - ). 
* Akademik ve idari personel ubs haricindeki diğer servislere(ebys, portal, vb.) eposta bilgileri ile giriş yaptığı için TC kimlik no ile giriş yapmasına gerek kalmaz. Ve dolasıyla 3. bir parolayı aklında tutmasına da gerek kalmaz. 
* Öğrenci topluluklara yönergesinde Madde 14/5 derki üniversite akademik ve idari personeli topluluk yönetim kurulu kararı ile fahri üye olabilirler. Şuan sistemde fahri üye rol tipi yok fakat yakın gelecekte bu durum topluluklar tarafından SKSDB'ye bildirileceği ve sisteme eklenmesinin isteneceği olası bir durumdur. Dolayısıyla ldap yine bu kullanıcıların login işlemlerini çözmenizi sağlayacaktır.

**LDAP'a geçilirse güncellenmesi gereken yerler**
* Şuan öğrenci ldap'ında öğrencinin mezun olması durumunda mail çalışmaya devam edebilir durumda bildiğim kadarıyla. Sessions#create bölümünde session oluşmadan ubs api ile öğrenci no gönderip dönüt olarak öğrencilik durumunun aktif olup olmadığı kontrol edilerek bu durum çözülebilir. 
* ubs api den öğrenci için full_name, birthday, faculty, program, program_id, crime alanları için veri çekecek şekilde güncellemelisiniz. full_name, birthday, faculty, program, program_id bunlar öğrenci ldap'ında var fakat ubs ile senkronize edilmiş durumda değil. Yani olası durumlar için veriler güvenli değil diyebiliriz. Ayrıca buraya şöyle bi çözüm üretebiliriz; bu doğruluğundan emin olamadığımız 5 alanın ldap tarafında ubs ile senkron hale getirebiliriz(bilgi işlem tarafında). 
* idari ve akademik personel için hiç ubs ye gitmeden tüm istediğiniz verileri Personel LDAP'ından alabilirsiniz. Böylelikle zaten yeterince hantal çalışan o sisteme bir iyilik yapmış olursunuz :)

Eğer geçilirse aşağıdaki bölümlerde sistemden kaldırılır:
![screenshot from 2017-02-01 02-10-31](https://cloud.githubusercontent.com/assets/9765995/22498115/3cd91128-e84e-11e6-9728-2d90d0b03c4d.png)
![screenshot from 2017-02-01 10-16-52](https://cloud.githubusercontent.com/assets/9765995/22498158/8abb10b2-e84e-11e6-98aa-9f1f92af2185.png)
![screenshot from 2017-02-01 10-16-44](https://cloud.githubusercontent.com/assets/9765995/22498159/8abcd690-e84e-11e6-89fe-ab86fc6fa0bf.png)
![screenshot from 2017-02-01 10-16-40](https://cloud.githubusercontent.com/assets/9765995/22498160/8ac35c36-e84e-11e6-81d9-3e46b6f763ae.png)

https://github.com/uzem/tbs/blob/master/app/services/ubs.rb#L33

**Comment by mustafaaltinkaynak** [comment]
Sinan merhaba,

Öğrenci ve personel için farklı LDAP servisleri çalışmaktadır. Öğrenci için konuşmak gerekirse UBS ile LDAP senkronizasyonunda bizler UBS üzerinden dönen bilgilere güvenmek zorundayız. Öğrenciye ilişkin tüm detaylı bilgilerin LDAP üzerinden aktarılmadığını unutmayalım. Bu aşamada uygulamanın tümünde UBS üzerinden bilgi dönüşleri sağlanmış ve kullanılmıştır. Öğrencinin aktif/pasif durumu da hazırlanan API üzerinden bilgi olarak dönen değerler arasındadır.

Personel içinse giriş mekanizması sanırım yönetici tarafından oluşturulan bilgi ile sağlanmaktadır. Yalnızca uygulama içerisinde personele ilişkin bilgiler UBS Personel sistemi üzerinden sağlanmaktadır. Yine bu aşamada UBS'ye güvenmek zorundayız. **Kişi üniversite personeli olup, e-postası açılmamış olabilir, dolayısıyla LDAP üzerinde de bilgisi yer almayabilir**. Önceliğimiz resmi kanallar marifetiyle yürütülen sistemin ürettiği verilere güvenmektir. Personelin e-posta bilgisine ihtiyaç duyulması halinde personele ait unique bilgi, personel LDAP sorgulanarak eşleşen e-posta bilgisi döndürülmektedir. Merkezi kimlik doğrulama mekanizması yazılması durumunda ki böyle bir şey düşünülüyor, bu durumda kesinlikle geçilebilir.

Tüm bunların yanı sıra SKS tarafından akademik ve idari personel için LDAP üzerinden kimlik doğrulama talep edilmesi durumunda API'yi hazırlayabilirim.

Emeğin ve desteğin için teşekkürler 👍

**Comment by roktas** [comment]
Temel sorun üniversite otomasyonunda SSO'ya imkan veren bir protokol ve backend store (LDAP sadece bir seçenek) olmaması.  Bu öyle kolayca gerçeklenecek bir özellik değil.  Tek başına LDAP'ın varlığı da kurtarmaz, erişimleri düzenleyen SAML, Shiboleth, OpenID Connect vs gibi bir protokol olmadıkça.  Herkesin kayıtlı olduğu bir LDAP olsa tüm sorunlar çözülecekmiş gibi bir kanaate varmayın diye yazıyorum.

Sonuç: Küheylan bulamadığımız ortamda eşek veya katırlarla idare edeceğiz.  Daha önemli ve büyük bir problemi, UZEM'in resmi olarak sorumlu olmadığı küçük bir projede çözmeye çalışmayın.  Daha büyük ve zor bir projenin işi bu.

İş kaydını kapatıyorum.  Sözünü ettiğim o büyük altyapı üniversiteye kazandırıldığında tekrar açarsınız iş kaydını.
